### ISSUE TITLE
Incorrect Directory Name or Structure

### ISSUE THREAD

**Issue by bkaminski** [LKarnai/LuciKarnai#1]
/resources/css/ should look like:

```
/resources/
    /css/
    /js/
    /inc/
    /img/
```

Is there a chance that on your machine that the folder name has a "/" in it and it's just one folder called "/resources/css", if that's the case, /resources/ should be a top level folder with containing folders as shown above.

**Comment by LKarnai** [comment]
Top level folder and sub-folders are free of any unnecessary "/" in code editor.  Reflects as follows:

> resources 
       > css
             - resets
             - style

Path showing as such in GitHub possibly due to empty directories. Will investigate further.

**Comment by bkaminski** [comment]
Just downloaded the .zip of the repo. There's nothing wrong... as you stated, it's a GitHub thing. When you hover over the "resources/css" link... it explains everything:

_"This path skips through empty directories"_

**Comment by LKarnai** [comment]
Glad we're on the same page.

Thanks!
