### ISSUE TITLE
Removal of unwanted border around navbar toggle button

### ISSUE THREAD

**Issue by LKarnai** [LKarnai/LuciKarnai#3]
Navbar toggle box/button encased in a dotted-line border when clicked and toggled.

**Comment by LKarnai** [comment]
Created CSS rule to remove the dotted-line border from the toggle button.

.navbar-toggler:focus {
  outline: none;

**Comment by bkaminski** [comment]
```
.navbar-toggler:focus {
    outline: none;
}
```

**Comment by LKarnai** [comment]
echo. print. 

Thanks!
